version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: cinema-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  profilepictures:
    build: ./profilepictures
    image: profilepictures_ms/profilepictures
    container_name: profilepictures-profilepictures
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: profilepictures.local

  db:
    image: mongo:3.3
    container_name: profilepicture-db
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/backup:rw